### ISSUE TITLE
ERROR：Towards Exemplar-Free Continual Learning in Vision Transformers: an Account of Attention, Functional and Weight Regularization

### ISSUE THREAD

**Issue by iamwangyabin** [Vision-Intelligence-and-Robots-Group/Best-Incremental-Learning#16]
Towards Exemplar-Free Continual Learning in Vision Transformers: an Account of Attention, Functional and Weight Regularization

Arxiv Link：https://arxiv.org/abs/2203.13167

**Comment by iamwangyabin** [comment]
Self-Sustaining Representation Expansion for Non-Exemplar Class-Incremental Learning(CVPR 2022)
Arxiv Link

**Comment by pinna526** [comment]
Thanks a lot! We have corrected these errors.
