### ISSUE TITLE
a little mistake

### ISSUE THREAD

**Issue by benmagnifico** [Vision-Intelligence-and-Robots-Group/Best-Incremental-Learning#17]
1.  in full paper list, the paper link of *MgSvF: Multi-Grained Slow vs. Fast Framework for Few-Shot Class-Incremental Learning* should be [[2006.15524\] MgSvF: Multi-Grained Slow vs. Fast Framework for Few-Shot Class-Incremental Learning (arxiv.org)](https://arxiv.org/abs/2006.15524)
2.  i wonder why the paper *Few-Shot Class-Incremental Learning via Relation Knowledge Distillation* by Songlin Dong published in aaai-21 has not been added

**Comment by pinna526** [comment]
Many thanks！The latest update seems to mix up some versions, I'm fixing the bug.If you find more, feel free to share.
