### ISSUE TITLE
ECCV

### ISSUE THREAD

**Issue by iamwangyabin** [Vision-Intelligence-and-Robots-Group/Best-Incremental-Learning#19]
FOSTER: Feature Boosting and Compression for Class-Incremental Learning
Few-Shot Class-Incremental Learning via Entropy-Regularized Data-Free Replay
Few-Shot Class-Incremental Learning from an Open-Set Perspective
Novel Class Discovery without Forgetting
Class-Incremental Learning with Cross-Space Clustering and Controlled Transfer
Transfer without Forgetting
FOSTER: Feature Boosting and Compression for Class-Incremental Learning

**Comment by pinna526** [comment]
Thanks,we have added these papers.
