### ISSUE TITLE
NeurIPS

### ISSUE THREAD

**Issue by iamwangyabin** [Vision-Intelligence-and-Robots-Group/Best-Incremental-Learning#20]
On Solving Class Incremental Learning in Continual Learning
Beyond Not-Forgetting: Continual Learning with Backward Knowledge Transfer 
Memory Efficient Continual Learning with Transformers
Margin-Based Few-Shot Class-Incremental Learning with Class-Level Overfitting Mitigation
Disentangling Transfer in Continual Reinforcement Learning 
Task-Free Continual Learning via Online Discrepancy Distance Learning
A simple but strong baseline for online continual learning: Repeated Augmented Rehearsal

**Comment by pinna526** [comment]
Thanks, we have added these articles.
