### ISSUE TITLE
Add a new toolbox about PTM-based incremental learning

### ISSUE THREAD

**Issue by sun-hailong** [Vision-Intelligence-and-Robots-Group/Best-Incremental-Learning#22]
Thanks authors for releasing this fantastic project! Would you please consider incorporating a new toolbox?
code: https://github.com/sun-hailong/LAMDA-PILOT
paper: https://arxiv.org/abs/2309.07117
Many thanks in advance!

**Comment by pinna526** [comment]
Thank you for your suggestion! We've already added the toolbox.
